/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class beauty_wsh_com_growdemo_jni_JniUtils */

#ifndef _Included_beauty_wsh_com_growdemo_jni_JniUtils
#define _Included_beauty_wsh_com_growdemo_jni_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     beauty_wsh_com_growdemo_jni_JniUtils
 * Method:    getStringFromC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_beauty_wsh_com_growdemo_jni_JniUtils_getStringFromC
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
