/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class beauty_wsh_com_theendofevangelion_jni_MyJniUtils */

#ifndef _Included_beauty_wsh_com_theendofevangelion_jni_MyJniUtils
#define _Included_beauty_wsh_com_theendofevangelion_jni_MyJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     beauty_wsh_com_theendofevangelion_jni_MyJniUtils
 * Method:    getStringFromCS2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_beauty_wsh_com_theendofevangelion_jni_MyJniUtils_getStringFromCS2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
